### ISSUE TITLE
ENTREVISTA A UN INGENIERO EN EL AREA DEL DESARROLLO DE SOFTWARE

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-2-entrevista-team-desarrollosoftware#1]
[Entrevista-Equipo-Saul-LuzArlethLB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-team-desarrollosoftware/files/12509375/Entrevista-Equipo-Saul-LuzArlethLB.pdf)

**Comment by Edwin14459** [comment]
**Calificado en equipo de acuerdo a la rubrica;**
Preparacion: **5/5**
Conocimiento ganado: **5/5**
Informe: **4/5** _(Faltó introducción)_
Redacción: **5/5**
Total=**19**

CALIFICACIÓN **19/20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
