### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-2-entrevista-team-desarrollosoftware#2]
[ENTREVISTA (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-team-desarrollosoftware/files/12544071/ENTREVISTA.1.pdf)

**Comment by ToniDepp** [comment]
**Preparación:** En base al reporte, las preguntas dichas por el equipo son de una respuesta algo interesante, así como la formulación 5 puntos de 5 puntos
**Conocimiento ganado:** En base al reporte, Captaron medianamente el mensaje, por ende, en base a la experiencia en el reporte del Ingeniero se puede pensar que es una persona bastante sabia en su ámbito 5 puntos de 5 puntos
**Informe:** El informe presenta varios detalles, pero haciendo énfasis en lo estructural es un poco “informal” 3 puntos de 5 puntos
**Redacción:** Falta de ortografía, un poco de incoherencia y sobre todo da la impresión de ser un poco informal 2 puntos de 5 puntos 
**Calificación:** 15/20
**Calificado por:** Eduardo Tomas

**Comment by josealfredo79** [comment]
Bien hecho y revisado
